local: false

api_addr: "http://your.ip:port"

task_space_id: anytimespace.id
task_reset: true

task_logs: true
task_log_props:
- A
- Few
- Prop
- Names
task_review_threshold: 5

pushover: true
pushover_journal_hours: 
- "0"
- "1"
- "2"
- "3"