services:
  anytype-automation:
    build: .
    restart: unless-stopped
    container_name: anytype-automation
    hostname: anytype-automation
    env_file:
      - .env.docker
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
    network_mode: host 
    depends_on:
       timetagger:
         condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${IP_ADDR}:8000/general/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  timetagger:
    image: ghcr.io/almarklein/timetagger
    container_name: timetagger
    volumes:
      - ./_timetagger:/root/_timetagger
    env_file:
      - .env.docker
    restart: unless-stopped
    network_mode: host 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${IP_ADDR}:81"]
      interval: 30s
      timeout: 10s
      retries: 3